import { ProvidersStore } from "@/store/provider";

import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TheHeader />

          <main className="container">
            <ProvidersStore>{children}</ProvidersStore>
          </main>

          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
